function ProgressSpinner() {
  return (
    <div className="progress-spinner">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="40.333"
        height="40.333"
        viewBox="0 0 40.333 40.333"
      >
        <g transform="translate(-1.833 -1.833)">
          <path
            d="M22,3.667V11"
            fill="none"
            stroke="#000"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="3.667"
          />
          <path
            d="M22,33v7.333"
            fill="none"
            stroke="#000"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="3.667"
          />
          <path
            d="M9.038,9.038l5.188,5.188"
            fill="none"
            stroke="#000"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="3.667"
          />
          <path
            d="M29.773,29.773l5.188,5.188"
            fill="none"
            stroke="#000"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="3.667"
          />
          <path
            d="M3.667,22H11"
            fill="none"
            stroke="#000"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="3.667"
          />
          <path
            d="M33,22h7.333"
            fill="none"
            stroke="#000"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="3.667"
          />
          <path
            d="M9.038,34.962l5.188-5.188"
            fill="none"
            stroke="#000"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="3.667"
          />
          <path
            d="M29.773,14.227l5.188-5.188"
            fill="none"
            stroke="#000"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="3.667"
          />
        </g>
      </svg>
    </div>
  );
}

export default ProgressSpinner;
