import { Html, Head, Main, NextScript } from "next/document";
import Navbar from "../components/Layout/Navbar/Navbar";

export default function Document(props: any) {
  console.log(props);

  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <body>
        <header>
          <Navbar />
        </header>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
